---
# tasks file for ansible-iotop

- block:
    - name: Install iotop packages
      become: yes
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        cache_valid_time: "{{ apt_cache_valid_time | default(omit) }}"
        install_recommends: no
      with_items:
        - "{{ iotop_packages }}"
        
  become: yes
  tags:
    - iotop
